<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "greentech_imports"
 *
 * Auto generated by Extension Builder 2014-03-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Imports',
	'description' => 'Versatile importer',
	'category' => 'module',
	'author' => 'Dirk Wenzel',
	'author_email' => 'dirk.wenzel@cps-it.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 1,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.4.0-7.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
