<?php

namespace CPSIT\T3importExport\Persistence;

use TYPO3\CMS\Extbase\Persistence\Generic\PersistenceManager as BasePersistenceManager;
use TYPO3\CMS\Extbase\Persistence\PersistenceManagerInterface;

class PersistenceManager extends BasePersistenceManager implements PersistenceManagerInterface
{
    public function add($object)
    {
        parent::add($object); // TODO: Change the autogenerated stub
    }

    public function persistAll()
    {
        parent::persistAll(); // TODO: Change the autogenerated stub
    }
}
